version: '3.9'
services:
  api:
    build: .
    volumes:
      - .:/src
    command: npm run serve
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    depends_on:
      - db
  db:
    image: "mysql"
    container_name: db
    restart: always
    env_file: ./.env
    ports:
        - "${DB_PORT}:${DB_PORT}"
    environment:
        MYSQL_ROOT_PASSWORD: "{$DB_PWD}"
        MYSQL_DATABASE: "{$DB_NAME}"
        MYSQL_PASSWORD: "{$DB_PWD}"
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
volumes:
  db-config:
  db-data:
networks:
  default:
    name: mb