version: '3.9'
services:
  api:
    build: .
    volumes:
      - .:/src
    command: npm run serve
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    depends_on:
      - mb-db
    links:
      - mb-db
  mb-db:
    image: postgres
    container_name: mb-db
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: "mb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
networks:
  default:
    name: mb